max_connections=150
shared_buffers=512MB
temp_buffers=8MB
work_mem=4MB
checkpoint_timeout=5min
effective_cache_size=256MB
fsync=on

hba_file=/var/db/postgres4/lab1/pg_hba.conf
commit_delay=200

random_page_cost=1.1

fsync=on

ssl=off
